services:
  backend:
    build:
      context: .docker/backend
      dockerfile: Dockerfile
    image: vsb-backend:latest
    container_name: vsb-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html:delegated
    ports:
      - "8000:8000"
    networks:
      - vsb-network

  frontend:
    image: oven/bun:latest
    container_name: vsb-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "bun install && bun dev"
    networks:
      - vsb-network

  postgres:
    image: postgres:latest
    container_name: vsb-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vsb-network

  adminer:
    image: adminer:latest
    container_name: vsb-adminer
    ports:
      - "8080:8080"
    networks:
      - vsb-network

  proxy:
    image: nginx:latest
    container_name: vsb-nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - vsb-network

networks:
  vsb-network:
    driver: bridge

volumes:
  postgres_data:
