gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 days
    ttl_update: true
    single_use: true
    cookie:
        enabled: true
        same_site: lax
        path: /
        domain: null
        http_only: true
        secure: true
        partitioned: false
        remove_token_from_body: true
    logout_firewall: api